;
; ----------------------------------
;   Template #1: for employee page
; ----------------------------------
;
SetDrawColor (64, 64, 64);
SetFillColor (200, 255, 160);
SetLineWidth (0.5);
Line (10, 14, 198, 14);
Line (10, 282, 198, 282);
SetFont ("Courier", "I", 10);                                           
Text (10, 287, "Employee report");                          
SetTextProp ("FOOTRNB1", 185, 287, -1, -1, 0, 0, 0,"Courier", "I", 9);  
;
SetTextColor (0, 0, 0);
SetFont ("Times", "B", 24);                                           
Text (15, 30, "Employee Details");                                      
;
SetLineWidth (0.3);
Rect (15, 50, 180, 85, "D");                                 
Rect (15, 50, 180, 10, "DF");                                 
SetFont ("Arial", "", 12);                                           
Text (85, 56, "Personal Information");                          
;                                                                     
SetFont ("Arial", "", 9);                                            
Text (20, 70, "First Name - Last  Name :");                                        
SetTextProp ("FIELD000", 65, 70, -1, -1, 0, 0, 0,"Courier","B", 10);  
Text (20, 77, "Maidden Name :");                                     
SetTextProp ("FIELD001", 65, 77, -1, -1, 0, 0, 0,"Courier","B", 10);  
Text (20, 84, "Birth Date :");                                     
SetTextProp ("FIELD002", 65, 84, -1, -1, 0, 0, 0,"Courier","B", 10);  
Text (20, 91, "Social Security Number :");                                
SetTextProp ("FIELD003", 65, 91, -1, -1, 0, 0, 0,"Courier","B", 10);  
Text (20, 98, "Education :");                                           
SetTextProp ("FIELD004", 65, 98, -1, -1, 0, 0, 0,"Courier","B", 10);  
Text (20, 105, "Personal Postal Address :");                              
SetTextProp ("FIELD005", 65, 105, -1, -1, 0, 0, 0,"Courier","B", 10); 
Text (20, 112, "Personal Email Address :");                                
SetTextProp ("FIELD006", 65, 112, -1, -1, 0, 0, 0,"Courier","B", 10); 
Text (20, 119, "Phone Number :");                                        
SetTextProp ("FIELD007", 65, 119, -1, -1, 0, 0, 0,"Courier", "B", 10);  
Text (20, 126, "Family Situation :");                                        
SetTextProp ("FIELD008", 65, 126, -1, -1, 0, 0, 0,"Courier", "B", 10);  
;
Rect (15, 150, 180, 68, "D");                                 
Rect (15, 150, 180, 10, "DF");                                 
SetFont ("Arial", "", 12);                                           
Text (85, 156, "Employer Information");                          
;                                                                     
;
SetFont ("Arial", "", 9);                                            
Text (20, 170, "Employee Number :");                                        
SetTextProp ("FIELD009", 65, 170, -1, -1, 0, 0, 0,"Courier", "B", 10);  
Text (20, 177, "Hiring Date :");                                        
SetTextProp ("FIELD010", 65, 177, -1, -1, 0, 0, 0,"Courier", "B", 10);  
Text (20, 184, "End of Contract :");                                        
SetTextProp ("FIELD011", 65, 184, -1, -1, 0, 0, 0,"Courier", "B", 10);  
Text (20, 191, "Company Branch :");                                        
SetTextProp ("FIELD012", 65, 191, -1, -1, 0, 0, 0,"Courier", "B", 10);  
Text (20, 198, "Contract Type :");                                        
SetTextProp ("FIELD013", 65, 198, -1, -1, 0, 0, 0,"Courier", "B", 10);  
Text (20, 205, "Position :");                                        
SetTextProp ("FIELD014", 65, 205, -1, -1, 0, 0, 0,"Courier", "B", 10);  
Text (20, 212, "Weekly Activity :");                                        
SetTextProp ("FIELD015", 65, 212, -1, -1, 0, 0, 0,"Courier", "B", 10);  
;
Rect (15, 235, 180, 40, "D");                                 
Rect (15, 235, 180, 10, "DF");                                 
SetFont ("Arial", "", 12);                                           
Text (85, 240, "Legal Notice");
;
SetXY (20, 248);                          
SetFont ("Arial", "I", 8);
SetMargins (20, 10, 18);                                           
Write (3.5, "Lorem ipsum dolor sit amet consectetuer wisi nec et id sociis. ");
Write (3.5, "Ante Praesent urna Vestibulum et Vestibulum elit odio pellentesque tincidunt ");
Write (3.5, "molestie. Vitae vitae non ut id et Vestibulum habitant dignissim vitae Phasellus.\n\n");

Write (3.5, "At semper ac ligula urna sed molestie sagittis quis porttitor quis. Sapien tellus Quisque ");
Write (3.5, "sit nibh risus ipsum vitae neque faucibus congue. Felis Lorem at felis id ligula ");
Write (3.5, "mauris pretium consectetuer at malesuada Phasellus Sed. Id Phasellus neque lobortis sodales ");
Write (3.5, " Vestibulum condimentum justo ridiculus malesuada convallis. Condimentum et tempus eget elit");
Write (3.5, " mattis Curabitur at.  Nulla Curabitur sapien lorem mauris Sed vitae accumsan Pellentesque malesuada sagittis.");
