<?php

class Student_model extends CI_Model
{

    public function __construct()
    {

        $this->load->database();
        $this->load->helper('url');
    }

    public function add_student()
    {
        $data = [

            'StudentReferenceID' => $this->input->post('StudentReferenceID'),
            'EducationYear' => $this->input->post('EducationYear'),
            'Semester' => $this->input->post('Semester'),
            'SchoolID' => $this->input->post('SchoolID'),
            'StudentID' => $this->input->post('StudentID'),
            'StudentStatusCode' => $this->input->post('StudentStatusCode'),
            'StudentPersonalID' => $this->input->post('StudentPersonalID'),
            'StudentPersonalIDTypeCode' => $this->input->post('StudentPersonalIDTypeCode'),
            'StudentPassportNumber' => $this->input->post('StudentPassportNumber'),
            'StudentPrefixCode' => $this->input->post('StudentPrefixCode'),
            'StudentNameThai' => $this->input->post('StudentNameThai'),
            'StudentMiddleNameThai' => $this->input->post('StudentMiddleNameThai'),
            'StudentLastNameThai' => $this->input->post('StudentLastNameThai'),
            'StudentNameEnglish' => $this->input->post('StudentNameEnglish'),
            'StudentMiddleEnglish' => $this->input->post('StudentMiddleEnglish'),
            'StudentLastNameEnglish' => $this->input->post('StudentLastNameEnglish'),
            'StudentGenderCode' => $this->input->post('StudentGenderCode'),
            'StudentBirthDate' => $this->input->post('StudentBirthDate'),
            'StudentBirthProvinceCode' => $this->input->post('StudentBirthProvinceCode'),
            'StudentNationalityCode' => $this->input->post('StudentNationalityCode'),
            'StudentRaceCode' => $this->input->post('StudentRaceCode'),
            'StudentReligionCode' => $this->input->post('StudentReligionCode'),
            'StudentLanguageCode' => $this->input->post('StudentLanguageCode'),
            'StudentOtherLanguageCode' => $this->input->post('StudentOtherLanguageCode'),
            'StudentBloodCode' => $this->input->post('StudentBloodCode'),
            'StudentWeight' => $this->input->post('StudentWeight'),
            'StudentHeight' => $this->input->post('StudentHeight'),
            'StudentOfficialAddressHouseRegisterID' => $this->input->post('StudentOfficialAddressHouseRegisterID'),
            'StudentOfficialAddressHouseNumber' => $this->input->post('StudentOfficialAddressHouseNumber'),
            'StudentOfficialAddressMoo' => $this->input->post('StudentOfficialAddressMoo'),
            'StudentOfficialAddressStreet' => $this->input->post('StudentOfficialAddressStreet'),
            'StudentOfficialAddressSoi' => $this->input->post('StudentOfficialAddressSoi'),
            'StudentOfficialAddressTrok' => $this->input->post('StudentOfficialAddressTrok'),
            'StudentOfficialAddressProvinceCode' => $this->input->post('StudentOfficialAddressProvinceCode'),
            'StudentOfficialAddressDistrictCode' => $this->input->post('StudentOfficialAddressDistrictCode'),
            'StudentOfficialAddressSubdistrictCode' => $this->input->post('StudentOfficialAddressSubdistrictCode'),
            'StudentOfficialAddressPostcode' => $this->input->post('StudentOfficialAddressPostcode'),
            'StudentOfficialAddressPhoneNumber' => $this->input->post('StudentOfficialAddressPhoneNumber'),
            'StudentCurrentAddressHouseRegisterID' => $this->input->post('StudentCurrentAddressHouseRegisterID'),
            'StudentCurrentAddressHouseNumber' => $this->input->post('StudentCurrentAddressHouseNumber'),
            'StudentCurrentAddressMoo' => $this->input->post('StudentCurrentAddressMoo'),
            'StudentCurrentAddressStreet' => $this->input->post('StudentCurrentAddressStreet'),
            'StudentCurrentAddressSoi' => $this->input->post('StudentCurrentAddressSoi'),
            'StudentCurrentAddressTrok' => $this->input->post('StudentCurrentAddressTrok'),
            'StudentCurrentAddressSubdistrictCode' => $this->input->post('StudentCurrentAddressSubdistrictCode'),
            'StudentCurrentAddressDistrictCode' => $this->input->post('StudentCurrentAddressDistrictCode'),
            'StudentCurrentAddressProvinceCode' => $this->input->post('StudentCurrentAddressProvinceCode'),
            'StudentCurrentAddressPostcode' => $this->input->post('StudentCurrentAddressPostcode'),
            'StudentCurrentAddressPhoneNumber' => $this->input->post('StudentCurrentAddressPhoneNumber'),
            'FatherPersonalID' => $this->input->post('FatherPersonalID'),
            'FatherPersonalIDTypeCode' => $this->input->post('FatherPersonalIDTypeCode'),
            'FatherPassportNumber' => $this->input->post('FatherPassportNumber'),
            'FatherPrefixCode' => $this->input->post('FatherPrefixCode'),
            'FatherNameThai' => $this->input->post('FatherNameThai'),
            'FatherMiddleNameThai' => $this->input->post('FatherMiddleNameThai'),
            'FatherLastNameThai' => $this->input->post('FatherLastNameThai'),
            'FatherNameEnglish' => $this->input->post('FatherNameEnglish'),
            'FatherMiddleNameEnglish' => $this->input->post('FatherMiddleNameEnglish'),
            'FatherLastNameEnglish' => $this->input->post('FatherLastNameEnglish'),
            'FatherPersonStatusCode' => $this->input->post('FatherPersonStatusCode'),
            'FatherPhoneNumber' => $this->input->post('FatherPhoneNumber'),
            'FatherOccupationCode' => $this->input->post('FatherOccupationCode'),
            'FatherSalary' => $this->input->post('FatherSalary'),
            'MotherPersonalID' => $this->input->post('MotherPersonalID'),
            'MotherPersonalIDTypeCode' => $this->input->post('MotherPersonalIDTypeCode'),
            'MotherPassportNumber' => $this->input->post('MotherPassportNumber'),
            'MotherPrefixCode' => $this->input->post('MotherPrefixCode'),
            'MotherNameThai' => $this->input->post('MotherNameThai'),
            'MotherMiddleNameThai' => $this->input->post('MotherMiddleNameThai'),
            'MotherLastNameThai' => $this->input->post('MotherLastNameThai'),
            'MotherNameEnglish' => $this->input->post('MotherNameEnglish'),
            'MotherMiddleNameEnglish' => $this->input->post('MotherMiddleNameEnglish'),
            'MotherLastNameEnglish' => $this->input->post('MotherLastNameEnglish'),
            'MotherPersonStatusCode' => $this->input->post('MotherPersonStatusCode'),
            'MotherPhoneNumber' => $this->input->post('MotherPhoneNumber'),
            'MotherOccupationCode' => $this->input->post('MotherOccupationCode'),
            'MotherSalary' => $this->input->post('MotherSalary'),
            'GuardianPersonalID' => $this->input->post('GuardianPersonalID'),
            'GuardianPersonalIDTypeCode' => $this->input->post('GuardianPersonalIDTypeCode'),
            'GuardianPassportNumber' => $this->input->post('GuardianPassportNumber'),
            'GuardianPrefixCode' => $this->input->post('GuardianPrefixCode'),
            'GuardianNameThai' => $this->input->post('GuardianNameThai'),
            'GuardianMiddleNameThai' => $this->input->post('GuardianMiddleNameThai'),
            'GuardianLastNameThai' => $this->input->post('GuardianLastNameThai'),
            'GuardianNameEnglish' => $this->input->post('GuardianNameEnglish'),
            'GuardianMiddleNameEnglish' => $this->input->post('GuardianMiddleNameEnglish'),
            'GuardianLastNameEnglish' => $this->input->post('GuardianLastNameEnglish'),
            'GuardianRelationCode' => $this->input->post('GuardianRelationCode'),
            'GuardianPhoneNumber' => $this->input->post('GuardianPhoneNumber'),
            'GuardianOccupationCode' => $this->input->post('GuardianOccupationCode'),
            'GuardianSalary' => $this->input->post('GuardianSalary'),
            'ParentMarriageStatusCode' => $this->input->post('ParentMarriageStatusCode'),
            'StudentBirthOrder' => $this->input->post('StudentBirthOrder'),
            'StudentElderBrotherAmount' => $this->input->post('StudentElderBrotherAmount'),
            'StudentElderSisterAmount' => $this->input->post('StudentElderSisterAmount'),
            'StudentYoungerBrotherAmount' => $this->input->post('StudentYoungerBrotherAmount'),
            'StudentYoungerSisterAmount' => $this->input->post('StudentYoungerSisterAmount'),
            'CurrentEducationLevelAdmissionYear' => $this->input->post('CurrentEducationLevelAdmissionYear'),
            'SchoolAdmissionYear' => $this->input->post('SchoolAdmissionYear'),
            'EducationLevelCode' => $this->input->post('EducationLevelCode'),
            'GradeLevelCode' => $this->input->post('GradeLevelCode'),
            'Classroom' => $this->input->post('Classroom'),
            'PartSchoolFlag' => $this->input->post('PartSchoolFlag'),
            'CurriculumID' => $this->input->post('CurriculumID'),
            'JourneyTypeCode' => $this->input->post('JourneyTypeCode'),
            'JourneyTime' => $this->input->post('JourneyTime'),
            'RockJourneyDistance' => $this->input->post('RockJourneyDistance'),
            'RubberJourneyDistance' => $this->input->post('RubberJourneyDistance'),
            'WaterJourneyDistance' => $this->input->post('WaterJourneyDistance'),
            'DisabilityCode' => $this->input->post('DisabilityCode'),
            'DisabilityDetail' => $this->input->post('DisabilityDetail'),
            'DisabilityLevelCode' => $this->input->post('DisabilityLevelCode'),
            'DisadvantagedCode' => $this->input->post('DisadvantagedCode'),
            'LackingBookFlag' => $this->input->post('LackingBookFlag'),
            'LackingFoodFlag' => $this->input->post('LackingFoodFlag'),
            'LackingStationeryFlag' => $this->input->post('LackingStationeryFlag'),
            'LackingUniformFlag' => $this->input->post('LackingUniformFlag'),
            'FamilyMonthlyIncome' => $this->input->post('FamilyMonthlyIncome'),
            'FamilyStatusCode' => $this->input->post('FamilyStatusCode'),
            'StudentLiveWithCode' => $this->input->post('StudentLiveWithCode'),
            'StateWelfareFlag' => $this->input->post('StateWelfareFlag'),
            'TalentCode' => $this->input->post('TalentCode')

        ];

        $result = $this->db->insert('STUDENT', $data);
        return $result;
    }


    //Delete Data Student
    public function delete_student($StudentReferenceID, $SchoolID)
    {
        $data = [

            'DeleteStatus' => '1'

        ];

        $result = $this->db->where('StudentReferenceID', $StudentReferenceID)->where('SchoolID', $SchoolID)->update('STUDENT', $data);
        return $result;
    }

    //Update Data Student
    public function update_student($StudentReferenceID, $SchoolID)
    {
        $data = [

            'EducationYear' => $this->input->post('EducationYear'),
            'Semester' => $this->input->post('Semester'),
            'SchoolID' => $this->input->post('SchoolID'),
            'StudentID' => $this->input->post('StudentID'),
            'StudentStatusCode' => $this->input->post('StudentStatusCode'),
            'StudentPersonalID' => $this->input->post('StudentPersonalID'),
            'StudentPersonalIDTypeCode' => $this->input->post('StudentPersonalIDTypeCode'),
            'StudentPassportNumber' => $this->input->post('StudentPassportNumber'),
            'StudentPrefixCode' => $this->input->post('StudentPrefixCode'),
            'StudentNameThai' => $this->input->post('StudentNameThai'),
            'StudentMiddleNameThai' => $this->input->post('StudentMiddleNameThai'),
            'StudentLastNameThai' => $this->input->post('StudentLastNameThai'),
            'StudentNameEnglish' => $this->input->post('StudentNameEnglish'),
            'StudentMiddleEnglish' => $this->input->post('StudentMiddleEnglish'),
            'StudentLastNameEnglish' => $this->input->post('StudentLastNameEnglish'),
            'StudentGenderCode' => $this->input->post('StudentGenderCode'),
            'StudentBirthDate' => $this->input->post('StudentBirthDate'),
            'StudentBirthProvinceCode' => $this->input->post('StudentBirthProvinceCode'),
            'StudentNationalityCode' => $this->input->post('StudentNationalityCode'),
            'StudentRaceCode' => $this->input->post('StudentRaceCode'),
            'StudentReligionCode' => $this->input->post('StudentReligionCode'),
            'StudentLanguageCode' => $this->input->post('StudentLanguageCode'),
            'StudentOtherLanguageCode' => $this->input->post('StudentOtherLanguageCode'),
            'StudentBloodCode' => $this->input->post('StudentBloodCode'),
            'StudentWeight' => $this->input->post('StudentWeight'),
            'StudentHeight' => $this->input->post('StudentHeight'),
            'StudentOfficialAddressHouseRegisterID' => $this->input->post('StudentOfficialAddressHouseRegisterID'),
            'StudentOfficialAddressHouseNumber' => $this->input->post('StudentOfficialAddressHouseNumber'),
            'StudentOfficialAddressMoo' => $this->input->post('StudentOfficialAddressMoo'),
            'StudentOfficialAddressStreet' => $this->input->post('StudentOfficialAddressStreet'),
            'StudentOfficialAddressSoi' => $this->input->post('StudentOfficialAddressSoi'),
            'StudentOfficialAddressTrok' => $this->input->post('StudentOfficialAddressTrok'),
            'StudentOfficialAddressProvinceCode' => $this->input->post('StudentOfficialAddressProvinceCode'),
            'StudentOfficialAddressDistrictCode' => $this->input->post('StudentOfficialAddressDistrictCode'),
            'StudentOfficialAddressSubdistrictCode' => $this->input->post('StudentOfficialAddressSubdistrictCode'),
            'StudentOfficialAddressPostcode' => $this->input->post('StudentOfficialAddressPostcode'),
            'StudentOfficialAddressPhoneNumber' => $this->input->post('StudentOfficialAddressPhoneNumber'),
            'StudentCurrentAddressHouseRegisterID' => $this->input->post('StudentCurrentAddressHouseRegisterID'),
            'StudentCurrentAddressHouseNumber' => $this->input->post('StudentCurrentAddressHouseNumber'),
            'StudentCurrentAddressMoo' => $this->input->post('StudentCurrentAddressMoo'),
            'StudentCurrentAddressStreet' => $this->input->post('StudentCurrentAddressStreet'),
            'StudentCurrentAddressSoi' => $this->input->post('StudentCurrentAddressSoi'),
            'StudentCurrentAddressTrok' => $this->input->post('StudentCurrentAddressTrok'),
            'StudentCurrentAddressSubdistrictCode' => $this->input->post('StudentCurrentAddressSubdistrictCode'),
            'StudentCurrentAddressDistrictCode' => $this->input->post('StudentCurrentAddressDistrictCode'),
            'StudentCurrentAddressProvinceCode' => $this->input->post('StudentCurrentAddressProvinceCode'),
            'StudentCurrentAddressPostcode' => $this->input->post('StudentCurrentAddressPostcode'),
            'StudentCurrentAddressPhoneNumber' => $this->input->post('StudentCurrentAddressPhoneNumber'),
            'FatherPersonalID' => $this->input->post('FatherPersonalID'),
            'FatherPersonalIDTypeCode' => $this->input->post('FatherPersonalIDTypeCode'),
            'FatherPassportNumber' => $this->input->post('FatherPassportNumber'),
            'FatherPrefixCode' => $this->input->post('FatherPrefixCode'),
            'FatherNameThai' => $this->input->post('FatherNameThai'),
            'FatherMiddleNameThai' => $this->input->post('FatherMiddleNameThai'),
            'FatherLastNameThai' => $this->input->post('FatherLastNameThai'),
            'FatherNameEnglish' => $this->input->post('FatherNameEnglish'),
            'FatherMiddleNameEnglish' => $this->input->post('FatherMiddleNameEnglish'),
            'FatherLastNameEnglish' => $this->input->post('FatherLastNameEnglish'),
            'FatherPersonStatusCode' => $this->input->post('FatherPersonStatusCode'),
            'FatherPhoneNumber' => $this->input->post('FatherPhoneNumber'),
            'FatherOccupationCode' => $this->input->post('FatherOccupationCode'),
            'FatherSalary' => $this->input->post('FatherSalary'),
            'MotherPersonalID' => $this->input->post('MotherPersonalID'),
            'MotherPersonalIDTypeCode' => $this->input->post('MotherPersonalIDTypeCode'),
            'MotherPassportNumber' => $this->input->post('MotherPassportNumber'),
            'MotherPrefixCode' => $this->input->post('MotherPrefixCode'),
            'MotherNameThai' => $this->input->post('MotherNameThai'),
            'MotherMiddleNameThai' => $this->input->post('MotherMiddleNameThai'),
            'MotherLastNameThai' => $this->input->post('MotherLastNameThai'),
            'MotherNameEnglish' => $this->input->post('MotherNameEnglish'),
            'MotherMiddleNameEnglish' => $this->input->post('MotherMiddleNameEnglish'),
            'MotherLastNameEnglish' => $this->input->post('MotherLastNameEnglish'),
            'MotherPersonStatusCode' => $this->input->post('MotherPersonStatusCode'),
            'MotherPhoneNumber' => $this->input->post('MotherPhoneNumber'),
            'MotherOccupationCode' => $this->input->post('MotherOccupationCode'),
            'MotherSalary' => $this->input->post('MotherSalary'),
            'GuardianPersonalID' => $this->input->post('GuardianPersonalID'),
            'GuardianPersonalIDTypeCode' => $this->input->post('GuardianPersonalIDTypeCode'),
            'GuardianPassportNumber' => $this->input->post('GuardianPassportNumber'),
            'GuardianPrefixCode' => $this->input->post('GuardianPrefixCode'),
            'GuardianNameThai' => $this->input->post('GuardianNameThai'),
            'GuardianMiddleNameThai' => $this->input->post('GuardianMiddleNameThai'),
            'GuardianLastNameThai' => $this->input->post('GuardianLastNameThai'),
            'GuardianNameEnglish' => $this->input->post('GuardianNameEnglish'),
            'GuardianMiddleNameEnglish' => $this->input->post('GuardianMiddleNameEnglish'),
            'GuardianLastNameEnglish' => $this->input->post('GuardianLastNameEnglish'),
            'GuardianRelationCode' => $this->input->post('GuardianRelationCode'),
            'GuardianPhoneNumber' => $this->input->post('GuardianPhoneNumber'),
            'GuardianOccupationCode' => $this->input->post('GuardianOccupationCode'),
            'GuardianSalary' => $this->input->post('GuardianSalary'),
            'ParentMarriageStatusCode' => $this->input->post('ParentMarriageStatusCode'),
            'StudentBirthOrder' => $this->input->post('StudentBirthOrder'),
            'StudentElderBrotherAmount' => $this->input->post('StudentElderBrotherAmount'),
            'StudentElderSisterAmount' => $this->input->post('StudentElderSisterAmount'),
            'StudentYoungerBrotherAmount' => $this->input->post('StudentYoungerBrotherAmount'),
            'StudentYoungerSisterAmount' => $this->input->post('StudentYoungerSisterAmount'),
            'CurrentEducationLevelAdmissionYear' => $this->input->post('CurrentEducationLevelAdmissionYear'),
            'SchoolAdmissionYear' => $this->input->post('SchoolAdmissionYear'),
            'EducationLevelCode' => $this->input->post('EducationLevelCode'),
            'GradeLevelCode' => $this->input->post('GradeLevelCode'),
            'Classroom' => $this->input->post('Classroom'),
            'PartSchoolFlag' => $this->input->post('PartSchoolFlag'),
            'CurriculumID' => $this->input->post('CurriculumID'),
            'JourneyTypeCode' => $this->input->post('JourneyTypeCode'),
            'JourneyTime' => $this->input->post('JourneyTime'),
            'RockJourneyDistance' => $this->input->post('RockJourneyDistance'),
            'RubberJourneyDistance' => $this->input->post('RubberJourneyDistance'),
            'WaterJourneyDistance' => $this->input->post('WaterJourneyDistance'),
            'DisabilityCode' => $this->input->post('DisabilityCode'),
            'DisabilityDetail' => $this->input->post('DisabilityDetail'),
            'DisabilityLevelCode' => $this->input->post('DisabilityLevelCode'),
            'DisadvantagedCode' => $this->input->post('DisadvantagedCode'),
            'LackingBookFlag' => $this->input->post('LackingBookFlag'),
            'LackingFoodFlag' => $this->input->post('LackingFoodFlag'),
            'LackingStationeryFlag' => $this->input->post('LackingStationeryFlag'),
            'LackingUniformFlag' => $this->input->post('LackingUniformFlag'),
            'FamilyMonthlyIncome' => $this->input->post('FamilyMonthlyIncome'),
            'FamilyStatusCode' => $this->input->post('FamilyStatusCode'),
            'StudentLiveWithCode' => $this->input->post('StudentLiveWithCode'),
            'StateWelfareFlag' => $this->input->post('StateWelfareFlag'),
            'TalentCode' => $this->input->post('TalentCode')

        ];

        $result = $this->db->where('StudentReferenceID', $StudentReferenceID)->where('SchoolID', $SchoolID)->update('STUDENT', $data);
        return $result;
    }
}
